sudo: false
language: rust
rust:
  - nightly
os:
  - linux
  - osx
cache:
  directories:
    - $HOME/.cargo
script:
  - |
    cd graphql
    cargo build &&
    cargo test
  - |
    cd graphql-language
    cargo build &&
    cargo test
notifications:
  email: false
