sudo: false
language: rust
rust:
  - stable
  - nightly
os:
  - linux
  - osx
cache:
  directories:
    - $HOME/.cargo
script:
  - cd graphql && cargo test
  - cd graphql-language && cargo test
notifications:
  email: false
